import type { ChangeRecord, Digest } from "./types.js";
import { summarizeChanges } from "./summarize.js";

function formatChangeSection(c: ChangeRecord): string {
  const lines = [
    `### ${c.competitorName} — ${c.category} (${c.sourceKind})`,
    "",
    `- **When:** ${c.detectedAt}`,
    `- **URL:** ${c.url}`,
    `- **Summary:** ${c.summary}`,
  ];
  if (c.isBaseline) {
    lines.push(`- **Note:** Baseline snapshot established (no prior content).`);
  }
  if (c.diffExcerpt) {
    lines.push("", "```diff", c.diffExcerpt.slice(0, 2000), "```");
  }
  return lines.join("\n");
}

export async function buildDigest(
  changes: ChangeRecord[],
  opts: { competitorId?: string; competitorName?: string } = {}
): Promise<Digest> {
  const generatedAt = new Date().toISOString();
  const label = opts.competitorName ?? "all competitors";
  const narrative = await summarizeChanges(changes, label);

  const byCategory = new Map<string, ChangeRecord[]>();
  for (const c of changes) {
    const list = byCategory.get(c.category) ?? [];
    list.push(c);
    byCategory.set(c.category, list);
  }

  const md: string[] = [
    `# CompetitorPulse Digest${opts.competitorName ? `: ${opts.competitorName}` : ""}`,
    "",
    `_Generated at ${generatedAt}_`,
    "",
    "## Executive summary",
    "",
    narrative,
    "",
  ];

  if (changes.length === 0) {
    md.push("_No changes in this run._", "");
  } else {
    md.push("## Changes by category", "");
    for (const cat of ["pricing", "feature", "blog", "other"] as const) {
      const list = byCategory.get(cat);
      if (!list?.length) continue;
      md.push(`## ${cat}`, "");
      for (const c of list) {
        md.push(formatChangeSection(c), "");
      }
    }
  }

  md.push("---", "_Generated by CompetitorPulse (MIT)_", "");

  return {
    generatedAt,
    competitorId: opts.competitorId,
    competitorName: opts.competitorName,
    markdown: md.join("\n"),
    changes,
  };
}
